api = "0.5"

[buildpack]
id = "fagianijunior/ssh-key"
version = "0.0.4"
name = "SSH Key Cloud Native Buildpack"
homepage = "https://github.com/fagianijunior/heroku-buildpack-ssh-key"
description = "Add an ssh key to your build."
keywords = ["ssh", "key", "git"]

[[buildpack.licenses]]
type = "MIT"

[[stacks]]
id = "heroku-18"

[[stacks]]
id = "heroku-20"

[[stacks]]
id = "io.buildpacks.stacks.bionic"